kind: Service
apiVersion: v1
metadata:
    name: burndownapiservice
spec:
    selector:
        app: burndownapi
    ports:
        - protocol: TCP
          port: 4001
          targetPort: 5001
          nodePort: 30005
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: burndownapi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: burndownapi
    template:
        metadata:
            labels:
                app: burndownapi
        spec:
            containers:
                - name: burndownapi
                  image: tomaboro/burndownapi:2.0
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 5001
                  resources:
                    requests:
                      cpu: 200m

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: burndownapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: burndownapi
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30