apiVersion: v1
kind: Namespace
metadata:
    name: production

---
kind: Service
apiVersion: v1
metadata:
    name: customerapiservice
spec:
    selector:
        app: customerapi
        namespace: production
    ports:
        - 
            protocol: "TCP"
            # Port accessible inside cluster
            port: 4000
            # Port to forward to inside the pod
            targetPort: 5001
            # Port accessible outside cluster
            nodePort: 30005
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: customerapi
    namespace: production
spec:
    replicas: 2
    selector:
        matchLabels:
            app: customerapi
    template:
        metadata:
            labels:
                app: customerapi
        spec:
            containers:
                -
                    name: customerapi
                    image: tomaboro/customerapi:1.2
                    imagePullPolicy: IfNotPresent
                    ports:
                    - 
                        containerPort: 5001